enable: "etcd"
etcd:
  rootDirectory: openim
  # [标准化部署] 原由 docker-compose CHATENV_DISCOVERY_ETCD_ADDRESS 注入，现固化到配置文件
  address: [ etcd:2379 ]
  username: ''
  password: ''

kubernetes:
  namespace: default

rpcService:
  chat: chat-rpc-service
  admin: admin-rpc-service
  bot: bot-rpc-service
