# List of Redis server addresses
# [标准化部署] 原由 docker-compose CHATENV_REDIS_ADDRESS 注入 (${REDIS_ADDRESS}=redis:6379)
address: [ redis:6379 ]
# Username for Redis authentication (leave blank if not used)
username: ''
# Password for Redis authentication
password: openIM123
# Enable or disable pipeline processing
enablePipeline: false
# Enable or disable cluster mode
clusterMode: false
# Database index to be used
db: 0
# Maximum number of retry attempts for a failed connection
maxRetry: 10
